scripts/tardis_download1.sh -ex binance $* -s \
1inchbtc,1inchbusd,1inchusdt,\
aavebtc,aavebusd,aaveeth,aaveusdt,\
acabtc,acabusd,acausdt,\
achbtc,achbusd,\
achusdt,\
acmbtc,acmbusd,acmusdt,\
adatusd,adausdc,adausdt,\
adxbtc,adxbusd,adxeth,adxusdt,\
aergobtc,aergobusd,aergousdt,\
aeurusdt,\
agibtc,agixbtc,agixbusd,agixusdt,\
agldbtc,agldbusd,agldusdt,\
aibtc,\
aifdusd,\
aionbtc,aioneth,aionusdt,\
aitusd,\
aiusdt,\
akrobtc,akrobusd,akrousdt,\
alcxbtc,alcxbusd,alcxusdt,\
algobtc,algobusd,algoeth,algofdusd,algotusd,algousdt,\
alicebtc,alicebusd,aliceusdt,\
alpacabtc,alpacabusd,alpacausdt,\
alphabtc,alphabusd,alphausdt,\
alpinebtc,alpinebusd,alpineusdt,\
ambbtc,ambbusd,ambusdt,\
ampbtc,ampbusd,ampusdt,\
ancbtc,ancbusd,ancusdt,\
ankrbtc,ankrbusd,ankrusdt,\
antbtc,antbusd,antusdt,\
anybtc,anybusd,anyusdt,\
apeaud,apebtc,apebusd,apeeth,apeusdt,\
api3btc,api3busd,api3usdt,\
appcbtc,\
aptbtc,aptbusd,apteth,aptusdt,\
arbbtc,arbeth,arbfdusd,arbtc,arbtusd,arbusd,arbusdc,arbusdt,\
ardrbtc,ardrusdt,\
arkbtc,arkbusd,arkmbtc,arkmtusd,arkmusdt,arkusdt,\
arpabtc,arpabusd,arpaeth,arpausdt,\
arusdt,\
asrbtc,asrbusd,asrusdt,\
astbtc,astrbtc,astrbusd,astreth,astrusdt,astusdt,\
atabtc,atabusd,atausdt,\
atmbtc,atmbusd,atmusdt,\
atombtc,atombusd,atometh,atomfdusd,atomusdc,atomusdt,\
auctionbtc,auctionbusd,auctionfdusd,auctionusdt,\
audbusd,\
audiobtc,audiobusd,audiousdt,\
audusdc,audusdt,\
autobtc,autobusd,autousdt,\
avabtc,avabusd,avausdt,\
avaxaud,avaxbtc,avaxbusd,avaxeth,avaxfdusd,avaxtusd,avaxusdc,avaxusdt,\
axsaud,axsbtc,axsbusd,axseth,axsusdt,\
badgerbtc,badgerbusd,badgerusdt,\
bakebtc,bakebusd,bakeusdt,\
balbtc,balbusd,balusdt,\
bandbtc,bandbusd,bandusdt,\
barbtc,barbusd,barusdt,\
batbtc,batbusd,bateth,batusdc,batusdt,\
bcdbtc,\
bchabusd,bchbtc,bchbusd,bchfdusd,bchpax,bchtusd,bchusdc,bchusdt,\
bdotdot,\
beambtc,beamusdt,beamxusdt,\
belbtc,belbusd,beleth,belusdt,\
betabtc,betabusd,betaeth,betausdt,\
bethbusd,betheth,bethusdt,\
bicobtc,bicobusd,\
bicousdt,\
bifibusd,bifiusdt,\
blurbtc,blurfdusd,blurusdt,\
blzbtc,blzbusd,blzeth,blzfdusd,blzusdt,\
bnbaud,bnbbtc,bnbbusd,bnbdai,bnbeth,bnbfdusd,bnbidrt,bnbngn,bnbpax,bnbtusd,bnbuah,\
bnbusdc,bnbusdp,bnbusdt,bnbust,bnbzar,\
bntbtc,bntbusd,bnteth,bntusdt,\
bnxbtc,bnxbusd,bnxusdt,\
bondbtc,bondbusd,bondeth,bondusdt,\
bonkfdusd,bonkusdt,\
bqxbtc,bqxeth,\
brdbtc,brdeth,\
bswbusd,bsweth,bswusdt,\
btcars,btcaud,btcbusd,btcdai,btcfdusd,btcgyen,btcidrt,btcngn,btcpax,btcpln,btcron,btcstbtc,btcstbusd,\
btcstusdt,btctusd,btcuah,btcusdc,btcusdp,btcusdt,btcust,btcvai,btczar,\
btgbtc,btgbusd,btgusdt,\
btsbtc,btsusdt,\
bttbusd,bttcbusd,bttcusdc,bttcusdt,btttrx,btttusd,bttusdc,bttusdt,\
burgerbusd,burgereth,burgerusdt,\
busdbvnd,busddai,busdpln,busdron,busduah,busdusdt,busdvai,busdzar,\
bzrxbtc,bzrxbusd,bzrxusdt,c98btc,\
c98busd,c98usdt,\
cakeaud,cakebtc,cakebusd,caketusd,cakeusdt,\
cdtbtc,cdteth,\
celobtc,celobusd,celousdt,\
celrbtc,celrbusd,celreth,celrusdt,\
cfxbtc,cfxbusd,cfxtusd,cfxusdt,\
chessbtc,chessbusd,chessusdt,\
chrbtc,chrbusd,chreth,chrusdt,\
chzbtc,chzbusd,chzusdt,\
citybtc,citybusd,cityusdt,\
ckbbtc,ckbbusd,ckbusdt,\
clvbtc,clvbusd,clvusdt,\
cndbtc,\
cocosbusd,cocosusdt,\
combousdt,compbtc,\
compbusd,comptusd,compusdt,\
cosbtc,cosbusd,cosusdt,\
cotibtc,cotibusd,cotiusdt,\
coverbusd,covereth,\
creambusd,creamusdt,\
crvbtc,crvbusd,crveth,crvusdt,\
ctkbtc,ctkbusd,ctkusdt,\
ctsibtc,ctsibusd,ctsiusdt,\
ctxcbtc,ctxcbusd,ctxcusdt,\
cvcbtc,cvcbusd,cvceth,cvcusdt,\
cvpbusd,cvpeth,cvpusdt,\
cvxbtc,cvxbusd,cvxusdt,\
cyberbtc,cybereth,cyberfdusd,cybertusd,cyberusdt,\
daibtc,daiusdt,\
darbtc,darbusd,dareth,darusdt,\
dashbtc,dashbusd,dasheth,dashusdt,\
databtc,databusd,dataeth,datausdt,\
dcrbtc,dcrusdt,\
degobtc,degobusd,degousdt,\
dentbusd,denteth,dentusdt,\
dexebusd,dexeeth,dexeusdt,\
dfbusd,\
dfeth,dfusdt,\
dgbbtc,dgbbusd,dgbusdt,\
diabtc,diabusd,diausdt,\
dltbtc,\
dntbtc,dntbusd,dntusdt,\
dockbtc,dockbusd,dockusdt,\
dodobtc,dodobusd,dodousdt,\
dogeaud,dogebtc,dogebusd,dogefdusd,dogetusd,dogeusdt,\
dotaud,dotbtc,dotbusd,doteth,dotfdusd,dotngn,dottusd,dotusdc,dotusdt,\
drepbtc,drepbusd,drepusdt,\
duskbtc,duskbusd,duskusdt,\
dydxbtc,dydxbusd,dydxeth,dydxfdusd,dydxusdt,\
easybtc,easyeth,\
edubtc,edutusd,eduusdt,\
egldbtc,egldbusd,egldeth,egldfdusd,egldron,egldusdt,\
elfbtc,elfbusd,elfeth,elfusdt,\
enjbtc,enjbusd,enjeth,enjusdt,\
ensbtc,ensbusd,ensusdt,\
eosaud,eosbtc,eosbusd,eoseth,eostusd,eosusdc,eosusdt,\
epsbtc,epsbusd,epsusdt,\
epxbusd,epxusdt,\
erdbtc,erdusdt,ernbusd,ernusdt,\
etcbtc,etcbusd,etceth,etcusdt,\
ethaud,ethbtc,ethbusd,ethdai,ethfdusd,ethngn,ethpax,ethpln,ethtusd,ethuah,ethusdc,ethusdp,\
ethusdt,ethust,ethzar,eurbusd,eurusdt,evxbtc,ezbtc,ezeth,farmbtc,farmbusd,farmeth,farmusdt,fdusdbusd,fdusdusdt,\
fetbtc,fetbusd,fetfdusd,fetusdt,\
fidabtc,fidabusd,fidausdt,\
filbtc,filbusd,fileth,filfdusd,filusdt,\
fiobtc,fiobusd,fiousdt,\
firobtc,firobusd,firoeth,firousdt,\
fisbtc,fisbusd,fisusdt,\
flmbtc,flmbusd,flmusdt,\
flokitusd,flokiusdt,\
flowbtc,flowbusd,flowusdt,\
fluxbtc,fluxbusd,fluxusdt,\
forbtc,forbusd,\
forthbtc,forthbusd,forthusdt,\
forusdt,\
frontbtc,frontbusd,fronteth,fronttusd,frontusdt,\
ftmaud,ftmbtc,ftmbusd,ftmeth,ftmfdusd,ftmusdt,\
fttbtc,fttbusd,ftteth,fttusdt,\
funbtc,funeth,funusdt,\
fxsbtc,fxsbusd,fxsusdt,\
galaaud,galabtc,galabusd,galaeth,galafdusd,galausdt,\
galbtc,galbusd,galeth,galusdt,\
gasbtc,gasbusd,gasfdusd,gasusdt,\
gbpbusd,gbpusdt,\
gftbusd,gftusdt,\
ghstbusd,ghsteth,ghstusdt,\
glmbtc,glmbusd,glmeth,glmrbtc,glmrbusd,glmrusdt,glmusdt,\
gmtaud,gmtbtc,gmtbusd,gmteth,gmtusdt,\
gmxbtc,gmxbusd,gmxusdt,\
gnobtc,gnobusd,gnousdt,\
gnsbtc,gnsusdt,\
gntbtc,gnteth,\
gobtc,\
grsbtc,grtbtc,\
grtbusd,grteth,grtusdt,\
gtcbtc,gtcbusd,gtcusdt,\
gtobtc,gtobusd,gtousdt,\
gvtbtc,\
gxsbtc,gxseth,gxsusdt,\
hardbtc,hardbusd,hardusdt,\
hbarbtc,hbarbusd,hbarusdt,\
hegicbusd,hegiceth,\
hftbtc,hftbusd,hftusdt,\
hifieth,hifiusdt,\
highbtc,highbusd,highusdt,\
hivebtc,hivebusd,hiveusdt,\
hntbtc,hntbusd,hntusdt,\
hookbtc,hookbusd,hookusdt,\
hotbusd,hoteth,hotusdt,\
icpbtc,icpbusd,icpeth,icpfdusd,icpusdt,icxbtc,icxbusd,icxeth,icxusdt,\
idbtc,\
idexbtc,idexbusd,idexusdt,\
idtusd,idusdt,\
ilvbtc,ilvbusd,ilvusdt,\
imxbtc,imxbusd,imxusdt,\
injbtc,injbusd,injeth,injfdusd,injtusd,injusdc,injusdt,\
iostbtc,iostbusd,iosteth,iostusdt,\
iotabtc,iotabusd,iotaeth,iotafdusd,iotausdt,\
iotxbtc,iotxbusd,iotxeth,iotxusdt,\
iqbusd,iqusdt,\
irisbtc,irisusdt,\
jasmybtc,jasmybusd,jasmyeth,jasmyusdt,\
joebtc,joebusd,joeusdt,\
jstbtc,jstbusd,jstusdt,\
jtofdusd,jtousdt,\
juvbtc,juvbusd,juvusdt,\
kavabtc,kavabusd,kavaeth,kavausdt,\
kdabtc,kdabusd,kdausdt,\
keepbtc,keepbusd,keepusdt,\
keybusd,keyeth,keyusdt,\
klaybtc,klaybusd,klayusdt,\
kmdbtc,kmdeth,kmdusdt,\
kncbtc,kncbusd,knceth,kncusdt,\
kp3rbusd,kp3rusdt,\
ksmaud,ksmbtc,ksmbusd,ksmeth,ksmusdt,\
laziobtc,laziobusd,laziousdt,\
ldobtc,ldobusd,\
ldofdusd,ldotusd,ldousdt,\
lendbtc,lendeth,lendusdt,\
leverbusd,leverusdt,\
linabtc,linabusd,linausdt,\
linkaud,linkbtc,linkbusd,linketh,linkfdusd,linkngn,linktusd,linkusdc,linkusdt,\
litbtc,litbusd,liteth,litusdt,\
lokabtc,lokabusd,lokausdt,\
loombtc,loombusd,loometh,loomusdt,\
lptbtc,lptbusd,lptusdt,\
lqtybtc,lqtyusdt,lrcbtc,\
lrcbusd,lrceth,lrcusdt,\
lskbtc,lskbusd,lsketh,lskusdt,\
ltcbtc,ltcbusd,ltceth,ltcfdusd,ltcngn,ltcpax,ltctusd,ltcuah,ltcusdc,ltcusdt,\
ltobtc,ltobusd,ltousdt,\
lunaaud,lunabtc,lunabusd,lunaeth,lunausdt,lunaust,\
luncbusd,luncusdt,\
magicbtc,magicbusd,magicusdt,\
manabtc,manabusd,manaeth,manausdt,\
maskbusd,maskusdt,\
maticaud,maticbtc,maticbusd,maticeth,maticfdusd,matictusd,maticusdc,maticusdt,\
mavbtc,mavtusd,mavusdt,\
mblbusd,mblusdt,\
mboxbtc,mboxbusd,mboxusdt,\
mcbtc,mcbusd,mcobtc,mcoeth,mcousdt,mcusdt,\
mdabtc,\
mdtbtc,mdtbusd,mdtusdt,mdxbtc,mdxbusd,mdxusdt,\
memeeth,memefdusd,\
memetusd,\
memeusdt,\
mfteth,mftusdt,\
minabtc,minabusd,minausdt,\
mirbtc,mirbusd,mirusdt,\
mithbtc,mithusdt,\
mkrbtc,mkrbusd,mkrusdt,\
mlnbtc,mlnbusd,mlnusdt,\
mobbtc,mobbusd,mobusdt,\
movrbtc,movrbusd,movrusdt,\
mthbtc,\
mtlbtc,mtlbusd,mtleth,mtlusdt,multibtc,multibusd,multiusdt,\
nanobtc,nanobusd,nanoeth,nanousdt,\
nasbtc,naseth,\
navbtc,naveth,\
nbsbtc,nbsusdt,\
nbtusdt,\
ncasheth,\
nearbtc,nearbusd,neareth,nearfdusd,nearusdt,\
neblbtc,neblbusd,nebleth,neblusdt,\
neobtc,neobusd,neoeth,neousdc,neousdt,\
nexobtc,nexobusd,nexousdt,\
nfpbtc,nfpfdusd,nfptusd,nfpusdt,\
nknbtc,nknbusd,nknusdt,\
nmrbtc,nmrbusd,nmrusdt,\
npxseth,npxsusdt,\
ntrnbtc,ntrnusdt,\
nuaud,\
nubtc,nubusd,\
nulsbtc,nulsbusd,nulsusdt,\
nuusdt,\
nxsbtc,\
oaxbtc,oaxusdt,\
oceanbtc,oceanbusd,oceanusdt,\
ogbtc,ogbusd,\
ognbtc,ognbusd,\
ognusdt,ogusdt,\
ombtc,ombusd,\
omgbtc,omgbusd,omgeth,omgusdt,\
omusdt,\
onebtc,onebusd,oneeth,oneusdt,\
ongbtc,ongusdt,\
ontbtc,ontbusd,onteth,ontusdt,\
ookibusd,ookieth,ookiusdt,\
opbtc,opbusd,\
opeth,\
opfdusd,\
optusd,opusdc,opusdt,\
ordibtc,ordifdusd,orditusd,ordiusdc,ordiusdt,\
ornbtc,ornbusd,ornusdt,\
osmobtc,osmobusd,osmousdt,\
ostbtc,osteth,\
oxtbtc,oxtbusd,oxtusdt,\
paxbusd,paxgbtc,paxgbusd,paxgusdt,paxusdt,\
pendlebtc,pendletusd,pendleusdt,\
peoplebtc,peoplebusd,peopleeth,peopleusdt,\
pepetusd,pepeusdt,\
perlbtc,perlusdt,\
perpbtc,perpbusd,perpusdt,\
phabtc,phabusd,phausdt,\
phbbtc,phbbusd,\
phbtusd,phbusdt,\
pivxbtc,pivxeth,pivxusdt,\
plabtc,plabusd,plausdt,\
pntbtc,pntusdt,\
poabtc,\
polsbtc,polsbusd,polsusdt,\
polybtc,polybusd,polyusdt,\
polyxbtc,polyxbusd,polyxusdt,\
pondbtc,pondbusd,pondusdt,\
portobtc,portobusd,portousdt,\
powrbtc,powrbusd,powreth,powrusdt,\
pptbtc,\
prombtc,prombusd,promusdt,\
prosbusd,proseth,prosusdt,\
psgbtc,psgbusd,\
psgusdt,\
pundixbusd,pundixeth,pundixusdt,\
pyrbtc,pyrbusd,pyrusdt,\
qibtc,qibusd,qiusdt,\
qkcbtc,qkcbusd,qkceth,qkcusdt,\
qlcbtc,qlceth,\
qntbtc,qntbusd,qntusdt,\
qspbtc,qspeth,\
qtumbtc,qtumbusd,qtumeth,qtumusdt,\
quickbtc,quickbusd,quicktusd,quickusdt,\
radbtc,radbusd,radusdt,\
rampbtc,rampbusd,rampusdt,\
rarebtc,rarebusd,rareusdt,\
raybusd,rayusdt,\
rcnbtc,rdnbtc,rdntbtc,rdnttusd,rdntusdt,\
reefbtc,reefbusd,reefusdt,\
reibusd,\
reieth,reiusdt,\
renbtc,renbtcbtc,renbtceth,renbusd,\
renusdt,repbtc,\
repeth,repusdt,\
reqbtc,reqbusd,requsdt,\
rgtbtc,rgtbusd,rgtusdt,\
rifbtc,rifusdt,\
rlcbtc,rlcbusd,rlceth,rlcusdt,\
rndrbtc,rndrbusd,rndrfdusd,rndrusdt,\
rosebtc,rosebusd,roseeth,roseusdt,\
rplbtc,rplbusd,rplusdt,\
rsrbtc,rsrbusd,rsrusdt,\
runeaud,runebtc,runebusd,runeeth,runefdusd,runetusd,runeusdt,\
rvnbtc,rvnbusd,rvnusdt,\
sandaud,sandbtc,sandbusd,sandeth,sandfdusd,sandusdt,\
santosbtc,santosbusd,santosusdt,\
scbtc,scbusd,\
sceth,\
scrtbtc,scrtbusd,scrteth,scrtusdt,\
scusdt,\
seibtc,seifdusd,seitusd,seiusdt,\
sfpbtc,sfpbusd,sfpusdt,\
shibaud,shibbusd,shibdoge,shibfdusd,shibtusd,shibuah,shibusdt,\
sklbtc,sklbusd,sklusdt,\
skybtc,\
slpbusd,\
slpeth,slpusdt,\
snglsbtc,\
snmbtc,snmbusd,\
sntbtc,sntbusd,snteth,sntusdt,\
snxbtc,snxbusd,snxeth,snxusdt,\
solaud,solbtc,solbusd,soleth,solfdusd,soltusd,solusdc,solusdt,\
spellbtc,spellbusd,spellusdt,\
srmbtc,srmbusd,srmusdt,\
ssvbtc,ssvbusd,ssveth,ssvtusd,ssvusdt,\
steembtc,steembusd,steemeth,steemusdt,\
stgbtc,stgbusd,stgusdt,\
stmxbtc,stmxbusd,stmxeth,stmxusdt,\
storjbtc,storjbusd,storjeth,storjusdt,\
stptbtc,stptbusd,stptusdt,\
straxbtc,straxbusd,straxeth,straxusdt,\
stxbtc,stxbusd,stxusdt,\
suibtc,suifdusd,suitusd,suiusdt,\
sunbtc,sunbusd,sunusdt,\
superbtc,superbusd,superfdusd,superusdt,\
susdbtc,susdusdt,\
sushibtc,sushibusd,sushiusdt,\
swrvbusd,\
sxpaud,\
sxpbtc,sxpbusd,sxpusdt,\
synbtc,synusdt,\
sysbtc,sysbusd,sysusdt,\
tbusd,\
tctbtc,\
tctusdt,\
tfuelbtc,tfuelbusd,tfuelusdt,\
thetabtc,thetabusd,thetaeth,thetausdt,\
tiabtc,tiatusd,tiausdt,\
tkobtc,tkobusd,tkousdt,\
tlmbtc,tlmbusd,tlmusdt,\
tomobtc,tomobusd,tomousdt,\
tornbtc,tornbusd,tornusdt,\
trbbtc,trbbusd,trbusdt,\
tribebtc,tribebusd,tribeusdt,\
troybtc,troybusd,troyusdt,\
trubtc,trubusd,truusdt,\
trxaud,trxbtc,trxbusd,trxeth,trxngn,trxpax,trxtusd,trxusdc,trxusdt,trxxrp,\
tusdbusd,\
tusdt,tusdusdt,\
tvkbtc,tvkbusd,tvkusdt,\
twtbtc,twtbusd,twtusdt,\
uftbusd,ufteth,uftusdt,\
umabtc,umabusd,umausdt,\
unfibtc,unfibusd,unfieth,unfiusdt,\
uniaud,unibtc,unibusd,unieth,uniusdt,\
usdcbusd,usdcusdt,usdpbusd,usdpusdt,usdtars,usdtbvnd,usdtdai,usdtgyen,usdtidrt,usdtngn,usdtpln,\
usdtron,usdtuah,usdtvai,usdtzar,ustbtc,ustbusd,ustcbusd,ustcfdusd,ustcusdt,ustusdt,\
utkbtc,utkbusd,utkusdt,\
vanrybtc,vanryusdt,\
vetbtc,vetbusd,veteth,vetusdt,\
vgxbtc,vgxeth,vgxusdt,\
viabtc,\
vibbtc,vibbusd,vibeth,vibusdt,\
vicbtc,vicusdt,\
vidtbtc,vidtbusd,vidtusdt,\
vitebtc,vitebusd,viteusdt,\
voxelbtc,voxelbusd,voxeleth,voxelusdt,\
vthousdt,\
wabibtc,\
wanbtc,\
waneth,wanusdt,\
wavesbtc,wavesbusd,waveseth,wavesusdt,\
waxpbtc,waxpbusd,waxpusdt,\
wbetheth,wbethusdt,\
wbtcbtc,wbtcbusd,wbtceth,wbtcusdt,\
winbusd,\
wingbtc,wingbusd,wingeth,wingusdt,\
wintrx,\
winusdc,winusdt,\
wldbtc,\
wldfdusd,wldusdt,\
wnxmbtc,wnxmusdt,\
woobtc,woobusd,woousdt,\
wprbtc,\
wrxbtc,wrxbusd,\
wrxusdt,\
wtcbtc,wtceth,wtcusdt,\
xecbusd,xecusdt,\
xembtc,xembusd,xemeth,xemusdt,\
xlmbtc,xlmbusd,xlmeth,xlmusdt,\
xmrbtc,xmrbusd,xmreth,xmrusdt,\
xnobtc,xnobusd,xnoeth,xnousdt,\
xrpaud,xrpbtc,xrpbusd,xrpeth,xrpfdusd,\
xrpngn,xrppax,xrptusd,xrpusdc,xrpusdt,\
xtzbtc,xtzbusd,xtzeth,xtzusdt,\
xvgbtc,xvgbusd,xvgeth,xvgtusd,xvgusdt,\
xvsbtc,xvsbusd,xvsusdt,\
yfibtc,yfibusd,yfiibtc,yfiibusd,yfiiusdt,yfiusdt,\
yggbtc,yggbusd,yggusdt,\
yoyobtc,\
zecbtc,zecbusd,zeceth,zecusdc,zecusdt,\
zenbtc,zenbusd,zeneth,zenusdt,\
zilbtc,zilbusd,zileth,zilusdt,\
zrxbtc,zrxbusd,zrxeth,zrxusdt,\
