scripts/tardis_download1.sh -ex huobi-dm $* -s \
ADA_CQ,ADA_CW,ADA_NQ,ADA_NW,\
BCH_CQ,BCH_CW,BCH_NQ,BCH_NW,\
BSV_CQ,BSV_CW,BSV_NQ,BSV_NW,\
BTC_CQ,BTC_CW,BTC_NQ,BTC_NW,\
DOT_CQ,DOT_CW,DOT_NQ,DOT_NW,\
EOS_CQ,EOS_CW,EOS_NQ,EOS_NW,\
ETC_CQ,ETC_CW,ETC_NQ,ETC_NW,\
ETH_CQ,ETH_CW,ETH_NQ,ETH_NW,\
FIL_CQ,FIL_CW,FIL_NQ,FIL_NW,\
LINK_CQ,LINK_CW,LINK_NQ,LINK_NW,\
LTC_CQ,LTC_CW,LTC_NQ,LTC_NW,\
TRX_CQ,TRX_CW,TRX_NQ,TRX_NW,\
USDT_CQ,USDT_CW,USDT_NQ,USDT_NW,\
XRP_CQ,XRP_CW,XRP_NQ,XRP_NW,\

