scripts/tardis_download1.sh -ex dydx $* -s \
AAVE-USD,ALGO-USD,AVAX-USD,ATOM-USD,ADA-USD,\
BTC-USD,BCH-USD,\
COMP-USD,CRV-USD,CELO-USD,\
DOGE-USD,DOT-USD,\
ETH-USD,EOS-USD,ETC-USD,ENJ-USD,\
FIL-USD,\
LINK-USD,LTC-USD,LUNA-USD,\
MATIC-USD,MKR-USD,\
NEAR-USD,\
RUNE-USD,\
SOL-USD,SNX-USD,SUSHI-USD,\
TRX-USD,\
UNI-USD,UMA-USD,\
XLM-USD,XMR-USD,XTZ-USD,\
YFI-USD,\
ZRX-USD,ZEC-USD,\
1INCH-USD,\
